# Uncomment the next line to define a global platform for your project

platform :ios, '11.2'

target 'iLoveBetsRus' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

pod 'Firebase/Analytics'
pod 'Firebase/Messaging'

pod 'Firebase/Core'
pod 'Firebase/Database'
pod 'Firebase/Auth'
pod 'Firebase/Storage'
pod 'JSQMessagesViewController'

pod 'ApphudSDK'


  # Pods for iLoveBetsRus

end
